-- 記事テーブル
BEGIN;

CREATE TABLE IF NOT EXISTS keep.articles(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(50) NOT NULL,
  title VARCHAR(120) NOT NULL,
  url VARCHAR(120),
  description VARCHAR(120),
  thumbnail VARCHAR(120),
  header VARCHAR(120),
  body VARCHAR(120),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;

COMMIT;